### ISSUE TITLE
flag to suppress events from namespace in console 

### ISSUE THREAD

**Issue by samarth-gupta-traceable** [kudobuilder/kuttl#156]
I am using kuttl to install and helm chart and verify that deployment and its pods are successfully started. 
Currently when test completes, we collectEvents gathers all events from namespace and prints it out to log.
Since I there are multiple pods started as part of deployment and each of them can have 10s of events, the console becomes noisy and even if test is passing it seems lot of things went wrong due to `WARNING` events from k8 for liveness and rediness. 

It would be great if we can make this control via flag option. 

this is done by code here: https://github.com/kudobuilder/kuttl/blob/fca4096b3e0002a15b1c9250041e79f816f0ccc6/pkg/test/case.go#L125

```
// CollectEvents gathers all events from namespace and prints it out to log
func (t *Case) CollectEvents(namespace string) {
	cl, err := t.Client(false)
	if err != nil {
		t.Logger.Log("Failed to collect events for %s in ns %s: %v", t.Name, namespace, err)
		return
	}

	eventsList := &eventsbeta1.EventList{}
```

sample noisy event logs
```
kuttl/harness/service-bootstrap: logger.go:42: 00:24:07 | service-bootstrap | 2020-07-02 23:20:51 +0530 IST	Warning	Unhealthy	Readiness probe failed: dial tcp 10.1.3.91:9092: connect: connection refused
    kuttl/harness/service-bootstrap: logger.go:42: 00:24:07 | service-bootstrap | 2020-07-02 23:20:51 +0530 IST	Warning	Unhealthy	Readiness probe failed: Get http://10.1.3.89:8081/: dial tcp 10.1.3.89:8081: connect: connection refused
    kuttl/harness/service-bootstrap: logger.go:42: 00:24:07 | service-bootstrap | 2020-07-02 23:20:51 +0530 IST	Warning	Unhealthy	Readiness probe failed:
    kuttl/harness/service-bootstrap: logger.go:42: 00:24:07 | service-bootstrap | 2020-07-02 23:20:52 +0530 IST	Warning	Unhealthy	Liveness probe failed: Get http://10.1.3.89:8081/: dial tcp 10.1.3.89:8081: connect: connection refused
```

**Comment by kensipe** [comment]
@samarth-gupta-traceable I like your thoughts around this... could you elaborate a bit more?   you mention a control flag...   What do you imagine here?  Could you give an example configuration of control?
I'll prioritize this if I can get some clarity around it.  thanks!

**Comment by kensipe** [comment]
thank you sir... I have a better understand of what you mean...      I expect that most users want the events as they provide a lot of context... but I don't see an issue to disable / suppress them.   I'm thinking we can make the switch more generic with a `--suppress-log` where `--suppress-log=Events` will allow for extension to additional suppression (not sure what that might be.. but I could see `--suppress-log=Commands` as well.
