### ISSUE TITLE
test harness should handle missing etcd and kube-api-server

### ISSUE THREAD

**Issue by jbarrick-mesosphere** [kudobuilder/kuttl#159]
**What happened**:

Currently, the test harness panics if it cannot find etcd and the kube-api-server and `start-control-plane` is set. We should handle this more nicely. Either we download them for the user or bail out with a nice error.

**Comment by kensipe** [comment]
This is not an issue any longer... It's been a year since the report... not sure what the change is.. but the current output does NOT panic and looks like a reasonable and understandable error.

```
 k kuttl test pkg/test/test_data
=== RUN   kuttl
    kuttl: harness.go:382: starting setup
    kuttl: harness.go:223: running tests with a mocked control plane (kube-apiserver and etcd).
    kuttl: harness.go:427: cleaning up
    kuttl: harness.go:502: fatal error getting client: failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory
--- FAIL: kuttl (0.01s)
```

Please reopen if you would like something different / better.
