### ISSUE TITLE
test step - pod log output via API

### ISSUE THREAD

**Issue by jmccormick2001** [kudobuilder/kuttl#16]
this is a feature request, for the kuttl API to provide a means to obtain the Pod log when a test step executes a Pod, the API would let you get back the Pod log via the API call to execute a Test Step.

Our use case includes running custom container images within a Test Step, those images will need to produce log output in a particular format (e.g. v1alpha2 in our case), then we can aggregate or do other processing on the test log output, our test logs from the pods will show various kinds of feedback useful for the end-user (e.g. suggestions or error descriptions).

**Comment by justinbarrick** [comment]
Thanks!

Is this a debugging feature (e.g. you just want to print them) or a testing feature where you want to use the output in an assert or later test step? Or both?

**Comment by jmccormick2001** [comment]
I'd like to get the Pod logs so I can relate them to the assertion result (pass/fail)...lets say a test fails, the assert will do its job, but the user will then wonder, why did this test fail?  the pod logs would give good insight into the failure cause...the pod logs could also show 'suggestions' that would not cause the test to fail per se, but prod the user towards best practices, this can arise when you do a validation test for example.

**Comment by justinbarrick** [comment]
I like that idea. So maybe we could have an option where you provide pod labels that should be streamed.

**Comment by kensipe** [comment]
This is coming up in other projects as well... In the other use case it looks like:

1. get the pod log output
2. assert on a regex match
3. success if the match hits
4. timeout failure if the match never hits
