### ISSUE TITLE
KUDO Operator testing library

### ISSUE THREAD

**Issue by mpereira** [kudobuilder/kuttl#164]
There should be a shared testing library that provides all necessary facilities for complex KUDO-based operators to have extensive and thorough integration tests.

Take a look at the [kudo-cassandra-operator testing facilities](https://github.com/mesosphere/kudo-cassandra-operator/tree/master/tests) to get a better understanding to how this differs from the current KUDO test harness, and provides functionality that is still not clear how to implement in the KUDO test harness, including a single verbose and useful test run output, useful for development and CI.

There's a [private protokep](https://docs.google.com/document/d/1PhjMiwG318nPkehDZ4oEMSb6zcKcZeO-/edit) for this in Google Drive.

**Comment by kensipe** [comment]
There was a lot going on with this issue... for 1 it was under KUDO and was missed when grooming KUTTL.  All the feature requests not already address had issues created for them so that we can close this issue and track each concept independently.
