### ISSUE TITLE
Add a Command TestAssert Collector

### ISSUE THREAD

**Issue by kensipe** [kudobuilder/kuttl#174]
Recently added is the ability to have a TestAssert Collector for pod logs... When configured it will get the configured pod logs and add it to the test log.   There is a new desire to be able to get information from a command to gather context for the assertion failure.

The request
```
Do you think it would make sense to add an onFailureCommand field (or something like that) to TestCase commands?
Some background:
A TestCase for an operator I'm working on has (among others) a command to kubectl kudo install the operator and an instance of it, and another command to run a script which:
1. polls on the instance .spec.planExecution.status to make sure it's COMPLETE , and
2. dump some debugging information (plan status and k8s events) in case it never gets to COMPLETE
I could get rid of (1) by using the --wait flag of kubectl kudo install , but I still need the debug stuff from (2) on failure.
```

1. commands could be used to get plan status (which is a kudo specific thing)
2. seems like there is a desire to get k8s events (perhaps an event collector)

This may mean rethinking collectors based on types:
1. pod log collector
2. events collector
3. command collector

others?

**Comment by porridge** [comment]
This sounds great!
One thing to note is that I would (also) need this to run if a `command` specified in a `kuttl-test.yaml` fails.
Not sure if I got this right (the docs seem to be a little [stale](kuttl.dev#20)), but it sounded to me like `collectors` can currently only be specified on a `TestAssert` which in turn can only be specified on the `NN-assert.yaml` level.

**Comment by kensipe** [comment]
That's correct... if we need a collector on the full collection of test suites... I like it... but needs to be thought out.  Thanks for making that clear.   It would be good to add those as well!
