### ISSUE TITLE
How to assert items in an array

### ISSUE THREAD

**Issue by sanjeevnewar2007** [kudobuilder/kuttl#233]
Hello,

I am raising this question under Issue as I am not getting the exact forum for the same.

**What happened**:
I am trying to add a device(server) using custom resource. The output contains various items. one of that is memory modules which is in the following format:

memoryModules:
    - isPresent: true
      model: DDR4
      size: 32768 MB
      slot: 1
      socket: CPU0_A0
      speed: 2133 MHz
      type: MEMORY
    - isPresent: true
      model: DDR4
      size: 129408 MB
      slot: 2
      socket: CPU0_A1
      speed: 2133 MHz
      type: DCPMM
.......

The memory modules is list of lets say 24 items.
When i try to assert only few of the selected items, i am getting error as below:

  <failure message="failed in step 1-install" type="">resource Server:kudo-test-composed-parakeet/example-server-58-10: .status.memoryModules: slice length mismatch: 3 != 24</failure>

**What you expected to happen**:
May i know how to assert specific items in the list?

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9+k3s1", GitCommit:"630bebf94b9dce6b8cd3d402644ed023b3af8f90", GitTreeState:"clean", BuildDate:"2020-09-17T19:05:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- KUTTL version (use `kubectl kuttl version`):
KUTTL Version: version.Info{GitVersion:"0.6.1", GitCommit:"4908507", BuildDate:"2020-08-25T18:22:14Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"

- Kernel (e.g. `uname -a`):
Linux kubemaster82 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Please let me know if I missed to provide any information.

Thanks,
Sanjeev

**Comment by ANeumann82** [comment]
This is currently not supported, but on the TODO-List. See https://github.com/kudobuilder/kuttl/issues/76

Not the most easy thing to implement though :)

**Comment by sanjeevnewar2007** [comment]
Thanks @ANeumann82 !!

**Comment by kensipe** [comment]
ah... Andreas provided an answer... this is a high priority to provide a solution.   As mentioned it is tracked on #76   Closing this as a duplicate.   Thanks for pushing on this!   It makes it more and more clear this is a very needed feature.
