### ISSUE TITLE
Harness try to use default ServiceAccount from "default" namespace even when a namespace is provided

### ISSUE THREAD

**Issue by PERES-Richard** [kudobuilder/kuttl#270]
Hello !

**What happened**:

Cannot start a single namespace kuttl test since the default ServiceAccount on default namespace is forbidden.

`fatal error getting client: serviceaccounts "default" is forbidden: User [...] cannot get resource "serviceaccounts" in API group "" in the namespace "default"`

(Full logs if needed)

```
$ k kuttl test --test ScaleUpAndDownDC -n my-namespace
=== RUN   kuttl
    harness.go:447: starting setup
    harness.go:248: running tests using configured kubeconfig.
I0204 11:03:51.560931 1219612 request.go:645] Throttling request took 1.042725216s, request: GET:[...]
    harness.go:495: cleaning up
    harness.go:550: removing temp folder: ""
    harness.go:576: fatal error getting client: serviceaccounts "default" is forbidden: User [...] cannot get resource "serviceaccounts" in API group "" in the namespace "default"
--- FAIL: kuttl (1.49s)
FAIL
```

**What you expected to happen**: (or more *wish to happen* maybe)

Harness try to get ServiceAccount default from default namespace (as a normal behavior) and if it's not found / forbidden, then it should/could try to find a default ServiceAccount to the provided namespace.

**How to reproduce it (as minimally and precisely as possible)**:

Use a cluster without a (or with a forbidden) ServiceAccount default in default namespace but a valid one in the namespace used for the single namespace test.

**Anything else we need to know?**:

I think this should be good for restricted cluster and will not change the normal/actual behavior of harness test but will enhance it.
Also I can contribute to implement a fix if you are ok. There is only 1 if statement to modify (here https://github.com/kudobuilder/kuttl/blame/86ae638ac86749852b1747b59958b9c7a4a23168/pkg/test/harness.go#L271)

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T20:52:22Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
- KUTTL version (use `kubectl kuttl version`):
```
KUTTL Version: version.Info{GitVersion:"0.7.2", GitCommit:"e310360", BuildDate:"2020-11-03T21:33:24Z", GoVersion:"go1.15.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: ```custom cluster with 'high' restriction rules```
- OS (e.g. from /etc/os-release): ```Ubuntu 20.04.1 LTS```
- Kernel (e.g. `uname -a`): ```Linux 5.4.0-41-generic```

Bisou from France & Casskop :)

**Comment by alenkacz** [comment]
Thanks for the report! I'll take a look at this

**Comment by alenkacz** [comment]
@PERES-Richard hi, yes, I like your proposed behavior, possibly the logic can go somewhere here https://github.com/kudobuilder/kuttl/blob/main/pkg/test/harness.go#L271

Do you want to contribute the fix?

**Comment by PERES-Richard** [comment]
Hello,

Yeah I would like to contribute to the fix 👍 

I will read the Contributing Guidelines and then I will create a PR.
