### ISSUE TITLE
Cannot grab the latest version (v0.9.0) of KUTTL by installing it using Krew

### ISSUE THREAD

**Issue by morningspace** [kudobuilder/kuttl#280]
**What happened**:
When I follow the [install instructions](https://kuttl.dev/docs/kuttl-test-harness.html#installation) to install KUTTL using Krew, I can see the KUTTL version is 0.8.0. However, the latest version of KUTTL as of now should be v0.9.0.

**What you expected to happen**:
Use Krew to install KUTTL should install the latest version.

**How to reproduce it (as minimally and precisely as possible)**:
- Run `krew install kuttl` to install kuttl using krew
- Run `kubectl kuttl -v`
- It returns 0.8.0, instead of 0.9.0.
 
**Environment**:
- Kubernetes version (use `kubectl version`):1.18
- KUTTL version (use `kubectl kuttl version`):0.8.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kensipe** [comment]
I just noticed this yesterday as well... on it!

**Comment by kensipe** [comment]
PR up: https://github.com/kubernetes-sigs/krew-index/pull/1073
