### ISSUE TITLE
ReportName is hard coded to "kuttl-test" due to which we are not able to provide customize name for the report

### ISSUE THREAD

**Issue by vikas-chourasia** [kudobuilder/kuttl#284]
https://github.com/kudobuilder/kuttl/blob/6de9356d102ff0db4234598762c9b38dad44fe84/pkg/kuttlctl/cmd/test.go#L114

**reportName** parameter in test suite yaml is not taking customized name as it is hardcoded in the test.go, kindly make that as a configurable parameter in test suite yaml. As we are running multiple suites one by one so all the reports generated by a previous suites are getting overwritten by the next suite.

**Sample Test Suite Yaml :**

```
apiVersion: kuttl.dev/v1beta1
kind: TestSuite
startKIND: true
kindContainers:
- your/image:latest
testDirs:
- tests/e2e/
reportName: abc-test
reportFormat: JSON
```

Thanks
Vikas

**Comment by codechennerator** [comment]
We're also experiencing this issue. Will there be updates on this?

**Comment by iblancasa** [comment]
How about using the `reportName` parameter from `kuttl-test.yaml`?  https://kuttl.dev/docs/testing/reference.html#testsuite

**Comment by kensipe** [comment]
this issue may be resolved with better documentation.   Adding to a milestone for resolution.
