### ISSUE TITLE
No report generated if skipClusterDelete is true

### ISSUE THREAD

**Issue by stevenbressey** [kudobuilder/kuttl#330]
**What happened**:

We're using our own preconfigured kind cluster to run test.
No test report is generated when skipClusterDelete flag is set to true.

The only way to get a report is to set skipClusterDelete to false

**What you expected to happen**:

Test report should always be generated when reportFormat is set, no matter the skipClusterDelete flag value.

**How to reproduce it (as minimally and precisely as possible)**:

Using the following kutt-test.yaml config file: 
```
apiVersion: kuttl.dev/v1beta1
kind: TestSuite
startKIND: false
kindContext: e2e-tests
skipClusterDelete: true
testDirs:
- tests/
timeout: 600
namespace: default
reportFormat: JSON
parallel: 1
```

Run one of the test in testDirs with the following command:

```
kubectl kuttl test --test mytest
```

No kuttl-test.json file is generated

**Anything else we need to know?**:

Report is not generated because of the return statement in the `h.TestSuite.SkipClusterDelete` condition: https://github.com/kudobuilder/kuttl/blob/d2cd0d5ec86a758ca4a13db032a89ae214d3d524/pkg/test/harness.go#L551

**Environment**:
- Kubernetes version (use `kubectl version`): v1.20.8
- KUTTL version (use `kubectl kuttl version`): 0.11.1
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release): Fedora
- Kernel (e.g. `uname -a`): 5.12.7-200
- Install tools:
- Others:

**Comment by kensipe** [comment]
Thank you so much for these report...  apologies in the delay
