### ISSUE TITLE
kuttl.dev down?

### ISSUE THREAD

**Issue by hassenius** [kudobuilder/kuttl#332]
**What happened**:

Can't seem to access kuttl.dev

Looking at isitdownrightnow I get the message `Parked`

https://www.isitdownrightnow.com/kuttl.dev.html

**What you expected to happen**:
Get access to kuttl documentation

**How to reproduce it (as minimally and precisely as possible)**:

Attempt to access https://kuttl.dev

**Comment by rishabh96b** [comment]
https://kuttl.dev/ is up now. Thanks for reporting @hassenius
