### ISSUE TITLE
CI is not run in PRs

### ISSUE THREAD

**Issue by iblancasa** [kudobuilder/kuttl#335]
**What happened**:
When a PR is opened, Circle CI is not reporting the status of the CI. I was not able to find the report in [the KUTTL Circle CI](https://app.circleci.com/pipelines/github/kudobuilder/kuttl?filter=all).

**Comment by iblancasa** [comment]
It would be nice if the CI is moved to GitHub actions since the developers would not need to create a Circle CI account to have CI in our forks.

I can work on this.

**Comment by kensipe** [comment]
To make this Issue more clear... the CI does kick off on PRs.   The Github portion "DCO Check" runs for all PRs.  The build, test portion from circleci only kicks off for committers on the project and not for all contributors. (this just recently came to this realization).   It is unclear why this is the case.  A support ticket was submitted to circleci. But I like the idea of moving to GH Actions and we should proceed in that direction.

**Comment by kensipe** [comment]
scheduling for next month.. but would prefer sooner.
