### ISSUE TITLE
Enable passing rest config to KUTTL

### ISSUE THREAD

**Issue by alifelan** [kudobuilder/kuttl#347]
We have been running our integration tests using KUTTL, and we are currently trying to run them in another environment, in which  there are some requirements in order to connect to the cluster. Before connecting, we need to handle tunneling and an SSH helper, which is done by setting a custom dial function on the rest config. With this, we can create a clientset to connect to the cluster.
However, KUTTL can't receive that clientset nor the rest config to connect. While taking a look at how KUTTL works, I saw that it also uses a rest config in pkg/test/harness.go, but it's not an exported variable. The Config() function has three options to create the config, but if a config is already set, it would be reused.
I tried running a test while making changes to a local KUTTL in which the test suite can receive a rest config, and Config() checks for its existence. This test ended up being able to connect to the cluster.

**Comment by kensipe** [comment]
I would love to understand more of what we are looking to do here.   You have a kubeconfig that will be generated and passed?   Couldn't you create the kubeconfig and set the KUBE_CONFIG env?

**Comment by alifelan** [comment]
Sure! To answer your first question, we are not generating a kubeconfig, but a rest config from an existing kubeconfig file, replacing its dial function with a custom ssh dial function, and passing that rest config to KUTTL. On the second one, since there are some network layers preventing the connection, it's not possible to set the KUBE_CONFIG envvar for KUTTL to connect.
