### ISSUE TITLE
events.k8s.io/v1beta1 Event is deprecated

### ISSUE THREAD

**Issue by aharbis** [kudobuilder/kuttl#373]
**What happened**: Installed latest `kuttl` and wrote a test suite, and ran the suite, warning is logged:

```
Warning: events.k8s.io/v1beta1 Event is deprecated in v1.22+, unavailable in v1.25+
```

**What you expected to happen**: No warnings about deprecated APIs

**How to reproduce it (as minimally and precisely as possible)**:

1. Run any `kuttl` test suite on Kubernetes 1.22+

**Anything else we need to know?**: n/a

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.23.5+b463d71`
- KUTTL version (use `kubectl kuttl version`): `0.12.1`
- Cloud provider or hardware configuration: OpenShift 4.10 on baremetal
- OS (e.g. from /etc/os-release): `Ubuntu 20.04.3 LTS`
- Kernel (e.g. `uname -a`): `5.4.0-109-generic`
- Install tools: n/a
- Others: n/a

**Comment by iblancasa** [comment]
This is not a problem because KUTTL is ready to use the `events.k8s.io/v1` API. We can maintain `events.k8s.io/v1beta1` for people using KUTTL with older Kubernetes versions.
