### ISSUE TITLE
Conditional execution of test steps

### ISSUE THREAD

**Issue by razvan** [kudobuilder/kuttl#379]
**What would you like to be added**:

I would like to run a test step only if a condition is met. This would allow me to install and test cluster specific resources.

For example, Helm has a way to check if a certain API is available in the cluster by querying the `capabilities` object and install custom resources of the corresponding `kind`.

Here is an snippet  that creates a SCC resource only when the `security.openshift.io/v1` API is available:

```
{{ if .Capabilities.APIVersions.Has "security.openshift.io/v1" }}
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: airflow-scc
...
{{ end }}
```

As you'd guess, the custom resource above is only created if the target cluster of the Helm chart is an OpenShift cluster.

In a similar fashion, I would like to be able to run a `kuttl` test step that creates  the same SCC only if the tests are running against OpenShift or to be more general, only if the API `security.openshift.io/v1` is available.

**Why is this needed**:

We write many tests and would like them to be reusable without modification across kubernetes implementations.

Currently, to run the same tests on KinD and OpenShift for example, we'd have to maintain two largely redundant code bases for each target cluster. This duplicates the effort to create and maintain these tests.

**Comment by iblancasa** [comment]
Duplicated by #400?

**Comment by erikgb** [comment]
> Duplicated by #400?

I am not sure if the issues are duplicates. This issue seems to address the need to conditionally disable _test steps_, while #400 asks for selectively disable _tests_.

**Comment by porridge** [comment]
We would also find it useful if `kuttl` had a way to conditionally skip files or steps. For exactly the same reasons as @razvan mentioned.
My best (but still horrible) idea for a workaround is to `cp -a` the test tree into a temporary directory and massaging it with a `find -name '*not-this-plaftorm*` -delete` before invoking `kuttl` there.

**Comment by eddycharly** [comment]
I guess you can use helm to template your test manifests.

**Comment by porridge** [comment]
There's always this possibility to treat a test suite as a *template* for the *actual* test suite.
But I like the idea sketched in https://kubernetes.slack.com/archives/CG3HTFCMV/p1687173186335739?thread_ts=1687170514.079399&cid=CG3HTFCMV

**Comment by razvan** [comment]
> My best (but still horrible) idea for a workaround is to `cp -a` the test tree into a temporary directory and massaging it with a `find -name '*not-this-plaftorm*` -delete`before invoking`kuttl` there.

It's basically what we are doing now in an automated way around `kuttl`. Our tests are made of two things:
1. A set of of [Jinja templates](https://github.com/stackabletech/druid-operator/tree/main/tests)
2. A [matrix of variables](https://github.com/stackabletech/druid-operator/blob/main/tests/test-definition.yaml) that we build a cartesian product from.

Then we use a simple [Python tool](https://github.com/stackabletech/beku.py) to generate the test suite.

**Comment by iblancasa** [comment]
We do something similar than @razvan but with Gomplate
