### ISSUE TITLE
When `kuttl` runs in a pod, `kubectl` run by it sees incorrect $KUBECONFIG

### ISSUE THREAD

**Issue by porridge** [kudobuilder/kuttl#393]
**What happened**:

When `kuttl` runs in a pod on kubernetes cluster `A`, but with the `KUBECONFIG` variable in its environment, pointing to cluster `B`:
- correctly applies manifests and checks assertions against cluster `B`,
- however any `kubectl` commands it runs from a `commands` or `collectors` inside a `TestAssert` seem have `KUBECONFIG` variable in their environments set to some weird value, as a result they find the kubeconfig for cluster `A` implicitly provided in the containing pod, and end up connecting to cluster `A` which is the wrong cluster

Example:

```
    logger.go:42: 06:11:18 | upgrade/20-upgrade-operator | running command: [kubectl logs --prefix -l app=central -n kuttl-test-desired-airedale --all-containers --tail=-1]
    logger.go:42: 06:11:18 | upgrade/20-upgrade-operator | W0901 06:11:18.221837    1761 loader.go:221] Config not found: /go/src/github.com/stackrox/stackrox/operator/kubeconfig
```

**What you expected to happen**:

The child commands should be fed the same `KUBECONFIG` as the parent `kuttl` has.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create two clusters, `A` and `B`.
2. Create a simple test suite that for example applies whatever resource (say a `ConfigMap`) and a `TestAssert` step which runs a `kubectl get` command for that resource
3. Run `kuttl` against the test suite in a pod on cluster `A` but feed it a kubeconfig for cluster `B`.

**Anything else we need to know?**:

One can work this around for `commands` by using another variable, say `REAL_KUBECONFIG` on the top level, and then saying `KUBECONFIG=$REAL_KUBECONFIG` in the command/script. However no such workaround is possible for `collectors`. :disappointed:

Potentially related tickets:
- https://github.com/kudobuilder/kuttl/issues/297
- https://github.com/kudobuilder/kuttl/issues/331

**Environment**:
- Kubernetes version (use `kubectl version`): OpenShift 4.11
- KUTTL version (use `kubectl kuttl version`): `0.13.0`

**Comment by gberche-orange** [comment]
@porridge @kensipe 
I see the following polluting error trace when running kuttl within the official Docker image within Kubernetes, even when specifying KUBECONFIG="" environment variable or unsetting it as advised into 

https://github.com/kudobuilder/kuttl/blob/2bcf5bebb8718af5df3cee5cb15702231093c8d3/Dockerfile#L13-L16
