### ISSUE TITLE
Docs: add missing documentation for test assert

### ISSUE THREAD

**Issue by eddycharly** [kudobuilder/kuttl#408]
Currently `TestAssert` is lacking documentation for the following elements:
- [collectors](https://github.com/kudobuilder/kuttl/blob/3a44c1b1da7f3e45fbcccf994f98b811d227e2db/pkg/apis/testharness/v1beta1/test_types.go#L126)
- [commands](https://github.com/kudobuilder/kuttl/blob/3a44c1b1da7f3e45fbcccf994f98b811d227e2db/pkg/apis/testharness/v1beta1/test_types.go#L128)

cc @chipzoller

**Comment by chipzoller** [comment]
Docs repo: https://github.com/kudobuilder/kuttl.dev

**Comment by chipzoller** [comment]
After an expansion of my previous PR, this will be additionally closed by https://github.com/kudobuilder/kuttl.dev/pull/60
