### ISSUE TITLE
Docs: add missing documentation for test collector

### ISSUE THREAD

**Issue by eddycharly** [kudobuilder/kuttl#409]
It looks like [TestCollector](https://github.com/kudobuilder/kuttl/blob/3a44c1b1da7f3e45fbcccf994f98b811d227e2db/pkg/apis/testharness/v1beta1/test_types.go#L173-L197) is not documented.

cc @chipzoller

**Comment by chipzoller** [comment]
These issues are probably better on the docs repo I'd image.

**Comment by eddycharly** [comment]
So right !
