### ISSUE TITLE
events.k8s.io/v1beta1 removal in Kubernetes 1.25

### ISSUE THREAD

**Issue by chipzoller** [kudobuilder/kuttl#414]
**What would you like to be added**:

Adapt kuttl to use new API version for Events in Kubernetes 1.25+

**Why is this needed**:

Test output shows kuttl is still getting events using the v1beta1 API version. As indicated, this is deprecated in 1.22 and removed in 1.25.

```
Warning: events.k8s.io/v1beta1 Event is deprecated in v1.22+, unavailable in v1.25+
```

**Comment by iblancasa** [comment]
Also, duplicated  #373

**Comment by iblancasa** [comment]
Maybe it makes sense to check both... instead being a fallback. I don't have a strong opinion about that.

**Comment by eddycharly** [comment]
If v1 is ok no need to call v1beta1, they will expose the same events (only the endpoints are different).

**Comment by chipzoller** [comment]
Right, v1 should be checked first, if not available, check v1beta1.
