### ISSUE TITLE
Update to controller-runtime v0.16+

### ISSUE THREAD

**Issue by blakebarnett** [kudobuilder/kuttl#473]
**Why is this needed**: Big performance improvements for clusters with many CRDs installed via the new lazy restmapper client.

https://github.com/kubernetes-sigs/controller-runtime/pull/2116

There are some breaking changes though:

https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.15.0

**Comment by porridge** [comment]
We should be careful about the (unintended?) semantic incompatibilities such as https://github.com/kubernetes-sigs/controller-runtime/issues/2354
