### ISSUE TITLE
Add "script" setting to commands that runs as a bash script

### ISSUE THREAD

**Issue by jbarrick-mesosphere** [kudobuilder/kuttl#50]
We should add a new setting to the commands struct called `script` that accepts a bash script as a string that we run. When running the script, we can set the `$NAMESPACE` and `$KUBECONFIG` variables. This will allow users to more easily write scripts inline when necessary.

```
apiVersion: kudo.dev/v1alpha1
kind: TestStep
commands:
- script: until ! kubectl get pod --namespace $NAMESPACE my-pod; do sleep 1; done
```

**Comment by jbarrick-mesosphere** [comment]
*note* the example there can be achieved using `kubectl wait --for=delete pod --namespace $NAMESPACE my-pod`

**Comment by kensipe** [comment]
I have the following questions:
1. currently Commands []Command `json:"commands"` is an array of Command I don't know how to union a type in an array (is that possible)...
2. we could keep it of type Command and add a "Script string " to the Command struct.. but that feels slightly awkward.. we to do if a command and a script is supplied?  we could some validation to error on it... or ignore one... but then I'm not sure if Background makes senses.  
3. What do you think of replacing script: for a specific script shell... I think I prefer to impl bash: instread... if we go that route perhaps we have a separate collections of scripts: like:

```
scripts:
  - bash: until ! kubectl get pod --namespace $NAMESPACE my-pod; do sleep 1; done
```

thoughts?

**Comment by kensipe** [comment]
the unfortunate part of a separate collection is ordering... you may want to run a command before a script or vise versa 🤔
