### ISSUE TITLE
[Bug]: Build fails with Go 1.23 because of changed testing.testDeps

### ISSUE THREAD

**Issue by stefanb** [kudobuilder/kuttl#546]
**What happened**:

build fails with 
````
# github.com/kudobuilder/kuttl/pkg/test/utils
  pkg/test/utils/testing.go:44:28: cannot use &testDeps{} (value of type *testDeps) as "testing".testDeps value in argument to testing.MainStart: *testDeps does not implement "testing".testDeps (missing method InitRuntimeCoverage)
````

**What you expected to happen**:

build to succeed.

**How to reproduce it (as minimally and precisely as possible)**:
1) Install Go 1.23 (rc1, rc2 or later)
2) build

**Anything else we need to know?**:

Related:
* found while building with https://github.com/Homebrew/homebrew-core/pull/175310
* similar issue: https://github.com/hofstadter-io/hof/issues/391

**Environment**:
- Kubernetes version (use `kubectl version`):
- KUTTL version (use `kubectl kuttl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by porridge** [comment]
Thanks for the report @stefanb !
Looks like we'll need something similar to https://github.com/hofstadter-io/hof/pull/392/files#diff-f08861a287bce287f8852024b94cd158021f70f1b18fdd846aabbde6d3bfc607R69 including making the `testing.MainStart` call versioned with build tags 🤔

**Comment by porridge** [comment]
@stefanb can you please check if https://github.com/kudobuilder/kuttl/pull/548 works for you?
