### ISSUE TITLE
Allow user impersonation as a cli flag

### ISSUE THREAD

**Issue by logan-bobo** [kudobuilder/kuttl#547]
**What would you like to be added**: The ability to pass an impersonation flag to `kuttl` to allow for the [impersonation of users](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation)

**Why is this needed**: There are situations where you may only have access to a single user that is able to impersonate other users that have privileged access. This would allow for the `--as` flag to be passed to `kuttl` to enable user impersonation. For example `kubectl kuttl test ... --as <user>`

Happy to pick this up if accepted ✋

**Comment by porridge** [comment]
I hope there is a library we can use to be compatible with kubectl w.r.t. translation of the command line flag value to the actual headers that the client needs to send? 

Otherwise (if we do the translation by hand) it would be a shame to become subtly incompatible over time.

**Comment by porridge** [comment]
Sounds good! It would be awesome if you could contribute this feature!

**Comment by logan-bobo** [comment]
@porridge I believe we can also now close this one out.

**Comment by porridge** [comment]
Done in https://github.com/kudobuilder/kuttl/pull/549
