### ISSUE TITLE
The `timeout` parameter is only applied to the assertion part of the step

### ISSUE THREAD

**Issue by zen-dog** [kudobuilder/kuttl#62]
**What happened**:
While working on a test that includes a webhook, I noticed that `timeout` parameter is not used when the test step fails in the apply-phase:

```
    harness.go:66: going to run test suite with timeout of 3000000 seconds for each step
    --- FAIL: kudo/harness (0.02s)
        --- FAIL: kudo/harness/terminal-failed-job (7.67s)
            logger.go:37: 14:51:05 | terminal-failed-job | Ignoring failjob-operator as it does not match file name regexp: ^(\d+)-([^.]+)(.yaml)?$
            logger.go:37: 14:51:05 | terminal-failed-job | Ignoring job-timeout-operator as it does not match file name regexp: ^(\d+)-([^.]+)(.yaml)?$
            logger.go:37: 14:51:05 | terminal-failed-job | Creating namespace: kudo-test-heroic-dodo
            logger.go:37: 14:51:05 | terminal-failed-job/0-install | starting test step 0-install
            logger.go:37: 14:51:05 | terminal-failed-job/0-install | running command:  {kubectl kudo install --instance failjob-operator-instance ./failjob-operator %!s(bool=true) %!s(bool=false) %!s(bool=false)}
            logger.go:37: 14:51:12 | terminal-failed-job/0-install | Error: failed to install instance failjob-operator-instance: installing Instance: Internal error occurred: failed calling webhook "instance-admission.kudo.dev": Post https://kudo-controller-manager-service.kudo-system.svc:443/admit-kudo-dev-v1beta1-instance?timeout=30s: dial tcp 10.103.201.124:443: connect: connection refused

            logger.go:37: 14:51:12 | terminal-failed-job/0-install | operator.kudo.dev/v1beta1/failjob-operator created
                operatorversion.kudo.dev/v1beta1/failjob-operator-0.1.0 created

            case.go:156: exit status 255
            case.go:159: failed in step 0-install
```

The [code suggests](https://github.com/kudobuilder/kuttl/blob/master/pkg/test/step.go#L393) that the `timeout` is only respected during the assertion phase of the step. I  often use the timeout to "pause" the execution of the failing step and look into the cluster (using `kubectl`). A number of k8s admission controllers might reject applied resources so it might be beneficial to extend timeout to the whole step and not just the assertion phase.

**What you expected to happen**:
The `timeout` should be applied to the whole step.

**How to reproduce it (as minimally and precisely as possible)**:
Using any step command that fails (e.g. `false`)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KUTTL version (use `kubectl kuttl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kensipe** [comment]
nice issue!   I think my mental model on this might be off... thanks for raising awareness on this.

We need to be clear on when we apply timeout.  is it:
1. For a teststep
2. For individual elements of a teststep
3. 1/2 step (test setup) and teststep assertion (are they separate or all part of the timeout?

I've recently added command timeouts and used the testsuite timeout for the command timeout.. but that is an expectation that each individual element of the step use this timeout.

We need to clearly define this and document this.
