### ISSUE TITLE
Fix Readme Doc

### ISSUE THREAD

**Issue by kensipe** [kudobuilder/kuttl#66]
We need a contribs doc...

in it we need to make sure devs are aware that we are dependent on kubebuilder... along with other dependents and requirements to get started.

**Comment by gerred** [comment]
https://github.com/kudobuilder/kuttl/blob/master/CONTRIBUTING.md - can we make this the canonical source of this?

**Comment by kensipe** [comment]
yes... yes!!!   good we have a contrib guide.. and it has details for kubebuilder.. awesome!  thanks @gerred  not sure how I missed it.  Now we need a link/ref from our readme.

**Comment by kensipe** [comment]
yeah... contrib doc is great... readme is not
